name: Auto-Grading for Number Checker

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install pytest
      run: pip install pytest
      working-directory: basics/conditional_statements/
    - name: Run tests with pytest
      run: pytest test_number_checker.py
      working-directory: basics/conditional_statements/
